const productsData = [
  {
    id: 1,
    category: "men",
    type: "topwear",
    name: "Unstitched Cotton Shirt Material",
    price: 499,
    originalPrice: 1299,
    color: "blue",
    style: "plain",
    material: "cotton",
    availability: "In stock",
    image: "/images/product1.jpg",
  },
  {
    id: 2,
    category: "women",
    type: "topwear",
    name: "Unstitched Silk Shirt Material",
    price: 799,
    originalPrice: 1599,
    color: "green",
    style: "checked",
    material: "silk",
    availability: "In stock",
    image: "/images/product2.jpg",
  },
  {
    id: 3,
    category: "kids",
    type: "topwear",
    name: "Unstitched Linen Shirt Material",
    price: 220,
    originalPrice: 1799,
    color: "red",
    style: "plain",
    material: "linen",
    availability: "In stock",
    image: "/images/product3.jpg",
  },
  {
    id: 4,
    category: "men",
    type: "bottomwear",
    name: "Unstitched Cotton Blend Shirt Material",
    price: 110,
    originalPrice: 1399,
    color: "black",
    style: "self-design",
    material: "cotton-blend",
    availability: "In stock",
    image: "/images/product4.jpg",
  },
];

export default productsData;
